name: Build lowfi for Debian

on:
  workflow_dispatch:
    inputs:
      lowfi_version:
        description: The version of lowfi to build.
        type: string
        required: true
      build_version:
        description: The build version.
        type: string
        required: true

permissions:
  contents: write

jobs:
  build-lowfi:
    name: Build
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout lowfi-debian
        uses: actions/checkout@v4

      - name: Build lowfi
        run: ./build.sh ${{ inputs.lowfi_version }} ${{ inputs.build_version }}
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: lowfi_*.deb


  release-lowfi:
    name: (Draft-)Release lowfi for Debian
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-lowfi
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Publish Release Draft
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: lowfi_*.deb
          name: ${{ inputs.lowfi_version }}+${{ inputs.build_version }}
          tag_name: ${{ env.RELEASE_TAG }}
          fail_on_unmatched_files: true
